name: npm Push

on: 
  push:
    branches:
      - main # Change this to your default branch

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.17.1

    - name: Build
      run: |
        npm install
        npm run build
        
    - name: Publish to npm
      run: |
        npm config set registry https://registry.npmjs.org
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    # - name: Publish to GitHub Package
    #   run: |
    #     npm config set registry https://npm.pkg.github.com
    #     npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    